In [8]:
import numpy as np

a = np.random.randint(1, 99, (3,5))
b = np.random.randint(7,44, (3,5))
print(a, b)


[[ 2 35 60 74 34]
 [ 6 26 30 94 76]
 [53  1  6 36  6]] [[14  8 27 15 13]
 [42 34 39 35 10]
 [25 38 43 15 26]]


In [10]:
norm = np.linalg.norm(a, axis = 0)
print(norm)
dot = np.dot(a.T,b)

[ 53.37602458  43.61192497  67.34983296 124.93198149  83.47454702]


creating word embeddings

https://towardsdatascience.com/creating-word-embeddings-coding-the-word2vec-algorithm-in-python-using-deep-learning-b337d0ba17a8

Glove - https://nlp.stanford.edu/projects/glove/

one hot encoding
distributed encoding
svd

